subroutinesaxpy(x,y,a,n)
useiso_fortran_env,only:rt=>real32
implicitnone
real(kind=rt),dimension(n)::x
real(kind=rt),dimension(n)::y
real(kind=rt)::a
integer::n
integer::i
!$omptargetteamsloopmap(to:x)
doi=1,n
y(i)=a*x(i)+y(i)
enddo
endsubroutinesaxpy
